### ISSUE TITLE
Heavy documentation unnecessary?

### ISSUE THREAD

**Issue by justanotherdot** [cdent/gabbi-multipart#2]
@cdent You have 'documentation' listed on the TODO for this but I reckon a simple quickstart in the README should be sufficient as there's nothing else to configure for the user of the handler. Thoughts?

**Comment by cdent** [comment]
I think the readme is probably fine. If we want to be extra friendly having the docs duplicated in the `__init__.py` would be nice, for people who want to use pydoc.

**Comment by justanotherdot** [comment]
Can you give an example for the `__init__.py`?

**Comment by cdent** [comment]
[wsgi-intercept](https://github.com/cdent/wsgi-intercept/blob/master/wsgi_intercept/__init__.py) has its basic docs in `__init__.py`. It's really just a matter of putting some content in a top level docstring. There are ways to make it more fancy (like automating README and __init__.py having the same content) but I'm not sure it is worth it in this case.

**Comment by justanotherdot** [comment]
Ah, I see, thanks for the link! The README is so small, seems like doing a pydoc approach this way would be overkill, so I'll close this question. If you feel I should go ahead and copy it in, though, let me know and I'll change it.
